### ISSUE TITLE
Have you seen this repository?

### ISSUE THREAD

**Issue by dennisdegreef** [iverberk/semver-updater#1]
https://github.com/tomzx/php-semver-checker

Might be interesting to use instead or integrate into this project :)

**Comment by iverberk** [comment]
Hi Dennis,

That package looks interesting but I'm a bit hesitant about all the automatic classifications. I think I'd rather classify them myself :-). The purpose of this package was to simply control (composer) version numbers in an automatic build. However, I did notice in the semver package (https://github.com/vierbergenlars/php-semver) that a console application was already included but not described in the documentation :-(

So I might retire this package quickly, or not, as it specifically does what I want without any overhead :-)

Thanks for the suggestion though!

**Comment by dennisdegreef** [comment]
Closed
